var GAME_LEVELS = [
  ["                                                                                ",
   "                                                y              y                ",
   "        y                                                                       ",
   "                                      y                                         ",
   "                                                                             y  ",
   "                                                          k      o              ",
   "            y                                                    xx             ",
   "                                                   xx      xx    x!!!xx         ",
   "                         xxxx       o o      xx                  x!!!x          ",
   "     y                                                           x!!!x          ",
   "                                   xxx                            xxx           ",
   "                                      xx                                    xx  ",
   "  xx                                        o         xxxx                   x  ",
   "  x            xx       o        k                                           x  ",
   "  x            xx                        xxxxx                             o x  ",
   "  x          xxxx                                     xxx     o       k      x  ",
   "  x  @       x  x       o                                                    x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxx           xxxxxxxxxxxxx       xxxxxxxxx  ",
   "                              x   x  x           x           x       x          ",
   "                              x o x   x!!!!!!!!!x            x!!!!!!!x          ",
   "                              xxxxx    x!!!!!!!x              x!!!!!x           ",
   "                                        xxxxxxx                xxxxx            ",
   "                                                                                ",
   "                                                                                "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    y               x!x  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              xxxxxxxxxxx      xxxx o                               x!x  ",
   "xxxxxxxxxxxxxx                                                        xxxxxxxxx                              x!x  ",
   "          xxxx                             xxxxxx    xxxx   xxx             xxxxxxx                          x!x  ",
   "           xx                       xxxx              !!     xxx                  xx              o   ok  o  x!x  ",
   "           xxxx                       xx              !! xxxx      o   o                                    xx!x  ",
   "            xxx           xxxx                        !!   xx   k                    xxx      xxxxxxxxxxxxxxx!!x  ",
   "    xxxxxxxxxxxxxx                           y        !!  xxx      x   x                   !!!!!!!!!!!!!!!!!!!xx  ",
   "xxxxxxxxxxxxxxx                                       !!     xx  xx         x              !xxxxxxxxxxxxxxxxxxx   ",
   "                        y           xxxxxx            !!      x!!!!!!!!!!!!xx      k       !                      ",
   "                                                      !!   y   xxxx!!!!!xxxx               !                      ",
   "       y                                       x     x!!          xxxxxxx        xxx       ! xxx                  ",
   "                  y                            x     x!!                         x x       ! x x        y         ",
   "                                               x     x!!                           x       ! x                    ",
   "                                    k          x     x!!                           xx      ! x                    ",
   "                 k                             xx    x!!                      k    x       ! x                    ",
   "                                               x     x!!    o  o     x   x         x       ! x                    ",
   "               xxx            xxx   xxx        x     x!!             x   x         x       ! x                    ",
   "              xx  x             x   x          x     x!!   xxxx      x   x   xxxxxxxxx     ! x                    ",
   "              x    x         x  x o x          x    xx!!             x   x   x             ! x                    ",
   "     @       xx     xxxx        x   x          x     x!!             x   x   x             ! x     y              ",
   "    xxx       x        x       ox   x          x     x!!             x   xxxxx   xxxxxx    ! x                    ",
   "    x x       x        x       xx o xx         x     x!!!!!!!!!!! xxxx     o     x x       ! x                    ",
   "  xxx x      xx        x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!!!  xx           x xx      ! x                y   ",
   "    x x       x        x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!!!   xxxxxxxxxxxxx x   o   !xx                    ",
   "    x x       x        x!!!!!x    o                 xx!!!!!!xx !!                   xxx!!!!!x                     ",
   "    x xx      x        x!!!!!x                     xx!!!!!!xx  !!                    xxxxxxx                      ",
   "    x x   o   x        x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !!                                                 ",
   "!!!!x x!!!xx!!x        x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !!                                                 ",
   "xxxxx xxxxxxxxx        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     !!                                                 "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                  y                     y     ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "              y                                                                                               ",
   "                                       yyy           y                                                        ",
   "                                                                                                              ",
   "                                         k                                                                    ",
   "                                                                                                              ",
   "                                       xxx                                                    y               ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!           o                         ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   o  o   x       xxx                            ",
   "                          y           x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxx  xxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "              y                       x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x          xx                    x!!!x                              ",
   "                                      x   x           x                     xxx                        y      ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x           x            xxx                                        ",
   "                                      x   x          xx           !!!!x                                       ",
   "                    y                 x   x           x     o     !xxx       xxx                              ",
   "                                     xx   xx          x           !         x!!!         o                    ",
   "                              o       x   x           x     y     !          xxxx       xxx                   ",
   "                                      x   x           x           !  x                 x!!!x                  ",
   "        y                    xxx xxx xxx xxx     o    x!!!!!!!!!!!!!!x                  !xx         y         ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                  !                     ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                  !                     ",
   "                             xx           xx                                         xxx!                     ",
   "  xxx                        xx           x       k         y                       x!!!!x               xxx  ",
   "  x x                         x    xo     x                                          xxxx                x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                  k        xx          x                              x x x                             x  ",
   "  x                                       x        xxxx      xxxx      xxx xxx                   k         x  ",
   "  x                xxx             o o    x                              x         xxx                    x  ",
   "  x               xxxxx       xx                                        xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx                                  x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx     o         o        o   xx xx                    xxx!!!!!!!!x  ",
   "  x      @          x     x!!!x           x!!!x   x!!!!x    x!!!!x    xx   xx                    x!!!!!!!!!x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                       y                          oooox       ",
   "                                                                                                  xxxxx       ",
   "           y                                          y                                                       ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                               k                    k        o o  xxx x       ",
   "                   xxx                                                                                xx      ",
   "       x !!! x                                                xxxxx x  xx xx  x x  xx x  xx xx  x xxxxx       ",
   "       x!!!!!x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x!!!!!x            y                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x!!!!!x                               y                 ox x   x x   x x   x x   x x   x x             ",
   "       !!!xxxx            o                                  xxxx x   x x   x x   x x   x x   x x    o        ",
   "       !!!                                                     xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx        ",
   "       !!!               xxx                              xy    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          ",
   "       !!                                                                                                     ",
   "       !!                                                                                               y     ",
   "       !!                                             yy                                                      ",
   "       !!          xxx         xxx                                                           k                ",
   "       !!                                                                                                     ",
   "       !!                 o              k                                      y      y                      ",
   "       !!                                                 yy     yy                                           ",
   "       !!    xxx         xxx         xxx                                 y                  y                 ",
   "     !!!! o                                                                                                   ",
   "  !!!!!!!xx                                                                         k                         ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                y                   ",
   "  x         x   x       x   x       x   x                                     y     y                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x                   k                 x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
